'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, CalendarDays, CircleDollarSign, Home, LogOut, Pencil, Plus, ReceiptText, Settings2, Sparkles, Trash2, Users, WalletCards, X } from 'lucide-react';

type Person = { id: string; name: string };
type Category = { id: string; name: string; monthlyLimit: number; carryover: number; color: string };
type Income = { id: string; personId: string; amount: number; source: string; date: string };
type Expense = { id: string; personId: string; categoryId: string; amount: number; note: string; date: string };
type BudgetData = { month: string; finalized: boolean; people: Person[]; categories: Category[]; incomes: Income[]; expenses: Expense[] };

const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' });
const colors = ['#2f7d64', '#e28555', '#d3ab41', '#6c7ecf', '#b4607c', '#4f9da6', '#7c6cab'];
const currentMonth = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`; };
const monthLabel = (value: string) => { const [y, m] = value.split('-').map(Number); return new Date(y, m - 1, 1).toLocaleDateString('en-US', { month: 'long', year: 'numeric' }); };

async function api<T = { error?: string }>(path: string, options: RequestInit = {}) {
  const response = await fetch(path, { ...options, headers: { 'content-type': 'application/json', 'x-household-pin': sessionStorage.getItem('pocketplan-pin') || '', ...(options.headers || {}) } });
  const json = await response.json() as T & { error?: string };
  if (!response.ok) throw new Error(json.error || 'Something went wrong');
  return json;
}

function Modal({ title, description, onClose, children }: { title: string; description?: string; onClose: () => void; children: React.ReactNode }) {
  return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && onClose()}><section className="modal" role="dialog" aria-modal="true" aria-label={title}><button className="icon-button modal-close" onClick={onClose} aria-label="Close"><X /></button><p className="eyebrow">PocketPlan</p><h2>{title}</h2>{description && <p className="modal-description">{description}</p>}{children}</section></div>;
}

function Setup({ configured, onReady }: { configured: boolean; onReady: () => void }) {
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true); setError(''); const values = Object.fromEntries(new FormData(event.currentTarget));
    try { await api(configured ? '/api/budget/login' : '/api/budget/setup', { method: 'POST', body: JSON.stringify(values) }); sessionStorage.setItem('pocketplan-pin', String(values.pin)); onReady(); }
    catch (e) { setError(e instanceof Error ? e.message : 'Could not continue'); } finally { setLoading(false); }
  }
  return <main className="gate-shell"><section className="gate-card"><div className="brand-mark"><WalletCards /></div><p className="eyebrow">Your money, on purpose</p><h1>{configured ? 'Welcome back.' : 'Build a budget for two.'}</h1><p>{configured ? 'Enter your shared household PIN to open your budget.' : 'Create a private household space, then give every dollar a job together.'}</p><form onSubmit={submit} className="stack-form">{!configured && <><label>Your name<input name="yourName" required placeholder="Alex" /></label><label>Partner’s name<input name="partnerName" required placeholder="Sam" /></label></>}<label>Shared household PIN<input name="pin" required minLength={4} maxLength={32} type="password" inputMode="numeric" placeholder="At least 4 characters" /></label>{error && <p className="form-error">{error}</p>}<button className="primary-button" disabled={loading}>{loading ? 'Opening…' : configured ? 'Open our budget' : 'Create our budget'}</button></form></section><aside className="gate-quote"><Sparkles /><blockquote>“A good budget isn’t a restriction. It’s a plan for the life you want to build.”</blockquote></aside></main>;
}

export default function HomePage() {
  const [status, setStatus] = useState<'loading' | 'setup' | 'login' | 'ready'>('loading');
  const [data, setData] = useState<BudgetData | null>(null); const [month, setMonth] = useState(currentMonth()); const [view, setView] = useState('together');
  const [modal, setModal] = useState<'expense' | 'income' | 'category' | 'settings' | 'finalize' | null>(null); const [editingTransaction, setEditingTransaction] = useState<Income | Expense | null>(null); const [saving, setSaving] = useState(false); const [editingCategory, setEditingCategory] = useState<string | null>(null); const [error, setError] = useState('');
  useEffect(() => { fetch('/api/budget/status').then(async r => await r.json() as { configured: boolean }).then(({ configured }) => setStatus(sessionStorage.getItem('pocketplan-pin') ? 'ready' : configured ? 'login' : 'setup')).catch(() => setStatus('setup')); }, []);
  useEffect(() => { if (status === 'ready') void load(); }, [status, month]);
  useEffect(() => {
    if (status !== 'ready' || !data) return;
    const context = (document as Document & { modelContext?: { registerTool: (tool: unknown, options?: { signal?: AbortSignal }) => void | Promise<void> } }).modelContext;
    if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    const register = (tool: unknown) => Promise.resolve(context.registerTool(tool, { signal: lifecycle.signal })).catch(() => undefined);
    void register({ name: 'add_budget_expense', title: 'Add budget expense', description: 'Record one expense for a household member in an existing envelope.', inputSchema: { type: 'object', properties: { personId: { type: 'string', enum: data.people.map(p => p.id) }, categoryId: { type: 'string', enum: data.categories.map(c => c.id) }, amount: { type: 'number', exclusiveMinimum: 0 }, note: { type: 'string' }, date: { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}$' } }, required: ['personId', 'categoryId', 'amount', 'note', 'date'], additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, execute: async (input: Record<string, unknown>) => { await api('/api/budget', { method: 'POST', body: JSON.stringify({ kind: 'expense', ...input }) }); await load(); return { status: 'recorded', amount: input.amount, note: input.note }; } });
    void register({ name: 'add_budget_income', title: 'Add budget income', description: 'Record one income entry for a household member.', inputSchema: { type: 'object', properties: { personId: { type: 'string', enum: data.people.map(p => p.id) }, amount: { type: 'number', exclusiveMinimum: 0 }, source: { type: 'string' }, date: { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}$' } }, required: ['personId', 'amount', 'source', 'date'], additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, execute: async (input: Record<string, unknown>) => { await api('/api/budget', { method: 'POST', body: JSON.stringify({ kind: 'income', ...input }) }); await load(); return { status: 'recorded', amount: input.amount, source: input.source }; } });
    return () => lifecycle.abort();
  }, [status, data, month]);
  async function load() { try { setData(await api<BudgetData>(`/api/budget?month=${month}`)); setError(''); } catch { sessionStorage.removeItem('pocketplan-pin'); setStatus('login'); } }
  const filteredIncome = useMemo(() => data?.incomes.filter(i => view === 'together' || i.personId === view) || [], [data, view]);
  const filteredExpenses = useMemo(() => data?.expenses.filter(i => view === 'together' || i.personId === view) || [], [data, view]);
  const totalIncome = filteredIncome.reduce((s, i) => s + i.amount, 0); const totalSpent = filteredExpenses.reduce((s, i) => s + i.amount, 0); const assigned = data?.categories.reduce((s, i) => s + i.monthlyLimit + i.carryover, 0) || 0; const available = totalIncome - totalSpent; const unassigned = totalIncome - (data?.categories.reduce((sum, category) => sum + category.monthlyLimit, 0) || 0);
  function openTransaction(kind: 'income' | 'expense', entry: Income | Expense | null = null) { setEditingTransaction(entry); setError(''); setModal(kind); }
  async function submit(kind: 'expense' | 'income' | 'category', event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (saving) return; setSaving(true); setError(''); const values = Object.fromEntries(new FormData(event.currentTarget)); try { await api('/api/budget', { method: editingTransaction && kind !== 'category' ? 'PUT' : 'POST', body: JSON.stringify({ kind, month, ...(kind !== 'category' && editingTransaction ? { id: editingTransaction.id } : {}), ...values }) }); setModal(null); setEditingTransaction(null); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not save'); } finally { setSaving(false); } }
  async function updateCategory(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editingCategory) return; setError(''); const values = Object.fromEntries(new FormData(event.currentTarget)); try { await api('/api/budget', { method: 'PUT', body: JSON.stringify({ kind: 'category', month, id: editingCategory, ...values }) }); setEditingCategory(null); setModal(null); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not save'); } }
  async function finalizeMonth() { if (data?.finalized || saving) return; setSaving(true); setError(''); try { await api('/api/budget', { method: 'POST', body: JSON.stringify({ kind: 'finalize', month }) }); setModal(null); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not finalize month'); } finally { setSaving(false); } }
  function nextMonth() { const [year, number] = month.split('-').map(Number); setMonth(`${number === 12 ? year + 1 : year}-${String(number === 12 ? 1 : number + 1).padStart(2, '0')}`); }

  async function remove(kind: 'expense' | 'income' | 'category', id: string) { if (!confirm(`Remove this ${kind}?`)) return; try { await api(`/api/budget?kind=${kind}&id=${id}&month=${month}`, { method: 'DELETE' }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not remove'); } }

  if (status === 'loading') return <div className="loading-screen"><div className="brand-mark"><WalletCards /></div><p>Opening PocketPlan…</p></div>;
  if (status !== 'ready') return <Setup configured={status === 'login'} onReady={() => setStatus('ready')} />;
  if (!data) return <div className="loading-screen"><div className="brand-mark"><WalletCards /></div><p>Gathering this month’s numbers…</p></div>;
  const viewName = view === 'together' ? 'Together' : data.people.find(p => p.id === view)?.name || 'Household';

  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark"><WalletCards /></span><span>PocketPlan</span></div><nav><button className="active"><Home />Overview</button><button disabled={data.finalized} onClick={() => openTransaction('expense')}><ReceiptText />Add expense</button><button disabled={data.finalized} onClick={() => { setEditingCategory(null); setModal('category'); }}><CircleDollarSign />New envelope</button></nav><div className="sidebar-bottom"><button onClick={() => setModal('settings')}><Settings2 />Budget settings</button><button onClick={() => { sessionStorage.removeItem('pocketplan-pin'); setStatus('login'); }}><LogOut />Lock budget</button><div className="partner-card"><Users /><div><strong>Shared with love</strong><span>{data.people.map(p => p.name).join(' + ')}</span></div></div></div></aside>
    <section className="workspace"><header className="topbar"><div><p className="eyebrow">Monthly plan</p><h1>{monthLabel(month)}</h1></div><div className="top-actions"><label className="month-picker"><CalendarDays /><input type="month" value={month} onChange={e => { if (e.target.value) { setData(null); setMonth(e.target.value); } }} /></label><button className="secondary-button" disabled={data.finalized} onClick={() => openTransaction('income')}><ArrowDownLeft />Add income</button><button className="primary-button compact" disabled={data.finalized} onClick={() => openTransaction('expense')}><Plus />Add expense</button></div></header>
      <section className={`month-status ${data.finalized ? 'is-finalized' : ''}`}><div><strong>{data.finalized ? 'Month finalized & locked' : 'Your month, ready to review'}</strong><p>{data.finalized ? 'These numbers are protected. Set your next month’s allowances when you’re ready.' : 'Edit your transactions, then finalize to protect this month’s budget and rollover.'}</p></div><button className="primary-button" onClick={() => { if (data.finalized) nextMonth(); else { setError(''); setModal('finalize'); } }}>{data.finalized ? 'Plan next month' : 'Finalize month'}</button></section>
      {error && !modal && <p className="form-error" role="alert">{error}</p>}
      <div className="view-tabs"><button className={view === 'together' ? 'active' : ''} onClick={() => setView('together')}><Users />Together</button>{data.people.map((p, i) => <button key={p.id} className={view === p.id ? 'active' : ''} onClick={() => setView(p.id)}><span className={`avatar avatar-${i}`}>{p.name[0]}</span>{p.name}</button>)}</div>
      <section className="welcome-row"><div><h2>Here’s your {viewName.toLowerCase()} plan.</h2><p>Give every dollar a job, then let unspent money roll forward.</p></div><span className={`status-chip ${unassigned >= 0 ? 'good' : 'bad'}`}>{unassigned >= 0 ? 'Fully funded' : 'Over-allocated'}</span></section>
      <section className="summary-grid"><article className="summary-card"><div className="summary-icon"><ArrowDownLeft /></div><p>Income</p><strong>{money.format(totalIncome)}</strong><span>{filteredIncome.length} entries this month</span></article><article className="summary-card"><div className="summary-icon peach"><WalletCards /></div><p>In envelopes</p><strong>{money.format(assigned)}</strong><span>Includes {money.format(Math.max(0, assigned - (data?.categories.reduce((s, i) => s + i.monthlyLimit, 0) || 0)))} rolled over</span></article><article className="summary-card"><div className="summary-icon gold"><ArrowUpRight /></div><p>Unassigned</p><strong className={unassigned < 0 ? 'over' : ''}>{money.format(unassigned)}</strong><span>{money.format(available)} remains after spending</span></article></section>
      <section className="content-grid"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">Your money, given a job</p><h2>Envelope balances</h2></div><button className="secondary-button small" disabled={data.finalized} onClick={() => { setEditingCategory(null); setError(''); setModal('category'); }}><Plus />New envelope</button></div><div className="envelope-list">{data.categories.map(c => { const spent = filteredExpenses.filter(e => e.categoryId === c.id).reduce((s, e) => s + e.amount, 0); const availableInEnvelope = c.monthlyLimit + c.carryover; const percent = Math.min(100, availableInEnvelope ? spent / availableInEnvelope * 100 : 0); return <div className="envelope" key={c.id}><div className="envelope-top"><span className="category-dot" style={{ background: c.color }} /><div><strong>{c.name}</strong><span>{money.format(spent)} spent of {money.format(availableInEnvelope)}</span></div><b className={spent > availableInEnvelope ? 'over' : ''}>{money.format(availableInEnvelope - spent)} left</b><button className="icon-button" disabled={data.finalized} onClick={() => { setEditingCategory(c.id); setError(''); setModal('category'); }} aria-label={`Edit ${c.name}`}><Pencil /></button></div><div className="progress-track"><span style={{ width: `${percent}%`, background: spent > availableInEnvelope ? '#c85d4d' : c.color }} /></div>{c.carryover > 0 && <small className="envelope-rollover">{money.format(c.carryover)} rolled over from last month</small>}</div>; })}{!data.categories.length && <div className="empty-state"><CircleDollarSign /><h3>No envelopes yet</h3><p>Create your first spending category.</p></div>}</div></article>
        <article className="panel activity-panel"><div className="panel-heading"><div><p className="eyebrow">Latest activity</p><h2>Recent spending</h2></div><button className="secondary-button small" onClick={() => { setError(''); setModal('settings'); }}>All transactions</button></div><div className="activity-list">{filteredExpenses.slice(0, 7).map(e => { const c = data.categories.find(x => x.id === e.categoryId); const p = data.people.find(x => x.id === e.personId); return <div className="activity" key={e.id}><span className="activity-icon" style={{ color: c?.color, background: `${c?.color}18` }}><ReceiptText /></span><div><strong>{e.note || c?.name}</strong><span>{c?.name} · {p?.name}</span></div><div className="activity-amount"><strong>-{money.format(e.amount)}</strong><span>{new Date(`${e.date}T12:00:00`).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</span></div><button className="icon-button" disabled={data.finalized} aria-label={`Edit ${e.note || c?.name}`} onClick={() => openTransaction('expense', e)}><Pencil /></button></div>; })}{!filteredExpenses.length && <div className="empty-state"><ReceiptText /><h3>Nothing spent yet</h3><p>Your newest expenses will show up here.</p></div>}</div></article></section>
    </section>
    {modal === 'expense' && <Modal title={editingTransaction ? "Edit expense" : "Add an expense"} description="Put this purchase into one of your monthly envelopes." onClose={() => setModal(null)}><form className="stack-form" onSubmit={e => submit('expense', e)}><label>Who spent it?<select name="personId" required defaultValue={editingTransaction?.personId}>{data.people.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Envelope<select name="categoryId" required defaultValue={editingTransaction && 'categoryId' in editingTransaction ? editingTransaction.categoryId : undefined}>{data.categories.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select></label><div className="form-row"><label>Amount<input name="amount" type="number" required min="0.01" step="0.01" placeholder="0.00" defaultValue={editingTransaction?.amount} /></label><label>Date<input name="date" type="date" required defaultValue={editingTransaction?.date || `${month}-01`} /></label></div><label>What was it for?<input name="note" defaultValue={editingTransaction && 'note' in editingTransaction ? editingTransaction.note : ''} required placeholder="Groceries at the market" /></label>{error && <p className="form-error">{error}</p>}<button className="primary-button" disabled={saving}>{saving ? 'Saving…' : 'Save expense'}</button></form></Modal>}
    {modal === 'income' && <Modal title={editingTransaction ? "Edit income" : "Add monthly income"} description="Track paychecks and other money for either person." onClose={() => setModal(null)}><form className="stack-form" onSubmit={e => submit('income', e)}><label>Who earned it?<select name="personId" required defaultValue={editingTransaction?.personId}>{data.people.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="form-row"><label>Amount<input name="amount" type="number" required min="0.01" step="0.01" placeholder="0.00" defaultValue={editingTransaction?.amount} /></label><label>Date<input name="date" type="date" required defaultValue={editingTransaction?.date || `${month}-01`} /></label></div><label>Income source<input name="source" defaultValue={editingTransaction && 'source' in editingTransaction ? editingTransaction.source : ''} required placeholder="Paycheck" /></label>{error && <p className="form-error">{error}</p>}<button className="primary-button" disabled={saving}>{saving ? 'Saving…' : 'Save income'}</button></form></Modal>}
    {modal === 'category' && <Modal title={editingCategory ? 'Edit envelope' : 'New envelope'} description={`Set the allowance for ${monthLabel(month)}. It carries forward until you change it in a later month; earlier months keep their amounts.`} onClose={() => { setModal(null); setEditingCategory(null); }}>{editingCategory ? (() => { const c = data.categories.find(category => category.id === editingCategory); if (!c) return null; return <form key={c.id} className="stack-form" onSubmit={updateCategory}><label>Envelope name<input name="name" required defaultValue={c.name} /></label><div className="form-row"><label>Monthly amount<input name="monthlyLimit" type="number" required min="0" step="0.01" defaultValue={c.monthlyLimit} /></label><label>Color<select name="color" defaultValue={c.color}>{colors.map(color => <option key={color} value={color}>{color}</option>)}</select></label></div>{error && <p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="secondary-button" onClick={() => { setModal(null); setEditingCategory(null); setError(''); }}>Cancel</button><button className="primary-button"><Pencil />Save changes</button></div></form>; })() : <form className="stack-form" onSubmit={e => submit('category', e)}><label>Envelope name<input name="name" required placeholder="Pets" /></label><div className="form-row"><label>Monthly amount<input name="monthlyLimit" type="number" required min="0" step="0.01" placeholder="150" /></label><label>Color<select name="color" defaultValue={colors[data.categories.length % colors.length]}>{colors.map(c => <option key={c} value={c}>{c}</option>)}</select></label></div>{error && <p className="form-error">{error}</p>}<button className="primary-button"><Plus />Add envelope</button></form>}</Modal>}
    {modal === 'finalize' && <Modal title={`Finalize ${monthLabel(month)}?`} description="This locks this month and all earlier months so later budget changes cannot alter your history. Finalization cannot be undone." onClose={() => { if (!saving) setModal(null); }}><div className="month-review"><div><span>Household income</span><strong>{money.format(data.incomes.reduce((sum, item) => sum + item.amount, 0))}</strong></div><div><span>Household spending</span><strong>{money.format(data.expenses.reduce((sum, item) => sum + item.amount, 0))}</strong></div><div><span>Rolling into next month</span><strong>{money.format(data.categories.reduce((sum, category) => sum + Math.max(0, category.monthlyLimit + category.carryover - data.expenses.filter(e => e.categoryId === category.id).reduce((total, e) => total + e.amount, 0)), 0))}</strong></div></div><p className="modal-description">Next month starts with these allowances. You can change them there without changing this month.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button className="secondary-button" disabled={saving} onClick={() => setModal('settings')}>Review transactions</button><button className="primary-button" disabled={saving} onClick={finalizeMonth}>{saving ? 'Finalizing…' : 'Finalize month'}</button></div></Modal>}
    {modal === 'settings' && <Modal title="All transactions" description={data.finalized ? "This month’s transactions are finalized and locked." : "Edit amounts, envelopes, dates, or household members."} onClose={() => setModal(null)}><h3 className="settings-title">Income</h3><div className="manage-list compact-list">{data.incomes.map(i => <div key={i.id}><strong>{i.source}</strong><span>{data.people.find(p => p.id === i.personId)?.name} · {money.format(i.amount)}</span><button className="icon-button" disabled={data.finalized} aria-label={`Edit ${i.source}`} onClick={() => openTransaction('income', i)}><Pencil /></button><button className="icon-button danger" disabled={data.finalized} aria-label={`Delete ${i.source}`} onClick={() => remove('income', i.id)}><Trash2 /></button></div>)}</div><h3 className="settings-title">Expenses</h3><div className="manage-list compact-list">{data.expenses.map(e => <div key={e.id}><strong>{e.note}</strong><span>{data.categories.find(c => c.id === e.categoryId)?.name} · {money.format(e.amount)}</span><button className="icon-button" disabled={data.finalized} aria-label={`Edit ${e.note}`} onClick={() => openTransaction('expense', e)}><Pencil /></button><button className="icon-button danger" disabled={data.finalized} aria-label={`Delete ${e.note}`} onClick={() => remove('expense', e.id)}><Trash2 /></button></div>)}</div>{error && <p className="form-error">{error}</p>}</Modal>}
  </main>;
}
